version: '3'

services:
  registerloginapp:
    container_name: registerloginapp.jar
    restart: always
    build: ./
    ports:
      - "3333:3333"
    networks:
      - registerloginapp-network
networks:
  registerloginapp-network:
    driver: bridge